# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# IMPORTANT: CodeRabbit only loads this config when the file is named ".coderabbit.yaml" and is located at the repository root.
language: en-GB
early_access: true
inheritance: true
reviews:
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  auto_apply_labels: true
  auto_assign_reviewers: true
  auto_review:
    drafts: true
    base_branches:
      - .*
knowledge_base:
  code_guidelines:
    filePatterns:
      - docs/tech_spec.md
      - docs/coding-guidelines.md
  mcp:
    usage: enabled
    # MCP server selection:
    # - This repository currently uses the CodeRabbit built-in MCP integration.
    # - Additional options (e.g., self-hosted MCP server URL(s)) can be added in a follow-up PR.
    #
    # Allowed tools / capabilities:
    # - Tool allow-listing is configured per MCP server in the CodeRabbit UI (Integrations → MCP Server).
    # - Current intent: enable all tools exposed by the selected MCP server.
    #
    # Data handling / authorization:
    # - MCP calls may send PR context (diffs, file paths, metadata) required to execute the enabled tools.
    # - Consider requiring explicit user approval for tool execution if your security posture demands it.
    #
    # Access controls (especially for private repos):
    # - Ensure the MCP server/integration is protected via appropriate authentication (OAuth/API keys)
    #   and network restrictions (firewall/IP allow-lists) where applicable.
issue_enrichment:
  auto_enrich:
    enabled: true
  labeling:
    auto_apply_labels: true
