# yaml-language-server: $schema=https://docs.coderabbit.ai/schema/schema.v2.json
# IMPORTANT: CodeRabbit only loads this config when the file is named ".coderabbit.yaml" and is located at the repository root.

language: en-GB
early_access: true
inheritance: true

reviews:
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  auto_apply_labels: true
  auto_assign_reviewers: true

  labeling_instructions:
    - label: bug
      instructions: >
        Apply when the PR fixes defects, crashes, incorrect behaviour, regressions,
        or incorrect outputs.
    - label: documentation
knowledge_base:
  mcp:
    usage: enabled
    documents:
      - tech_spec.md
      - DashFin-financial-asset-relationship-db-wiki-v2.md

  code_guidelines:
    enabled: true
        developer guides, with no substantive runtime behaviour change.
    - label: security
      instructions: >
        Apply when the PR addresses security issues, mitigates vulnerabilities,
        hardens authentication/authorisation, or improves secret handling.

  auto_review:
    usage: enabled
    filePatterns:
      - tech_spec.md
      - DashFin-financial-asset-relationship-db-wiki-v2.md
    drafts: true
    base_branches:
      - ".*"

knowledge_base:
reviews:
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  auto_apply_labels: true
  auto_assign_reviewers: true

  labeling_instructions:
    - label: bug
      instructions: >
        Apply when the PR fixes defects, crashes, incorrect behaviour, regressions,
        or incorrect outputs.
    - label: documentation
      instructions: >
        Apply when the PR only changes documentation, comments, READMEs, or
        developer guides, with no substantive runtime behaviour change.
    - label: security
      instructions: >
        Apply when the PR addresses security issues, mitigates vulnerabilities,
        hardens authentication/authorisation, or improves secret handling.

  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - ".*"

knowledge_base:
  mcp:
    usage: enabled
    filePatterns:
      - tech_spec.md
      - DashFin-financial-asset-relationship-db-wiki-v2.md

  code_guidelines:
    enabled: true
    filePatterns:
      - tech_spec.md
      - DashFin-financial-asset-relationship-db-wiki-v2.md

  code_guidelines:
    enabled: true
    filePatterns:
      - tech_spec.md
      - DashFin-financial-asset-relationship-db-wiki-v2.md

issue_enrichment:
  auto_enrich:
    enabled: true
  labeling:
    auto_apply_labels: true
